#!/bin/sh
# preinst script for ossec-hids-agent
# Santiago Bassett <santiago.bassett@gmail.com>
# 03/25/2014

set -e

case "$1" in
    install|upgrade)

    ;;

    abort-upgrade)

    ;;

    *)
        echo "preinst called with unknown argument '$1'" >&2
        exit 1

    ;;

esac

exit 0
