#!/bin/sh
# preinst script for ossec-hids

set -e

case "$1" in
    install|upgrade)
      # TODO: Backup rules not included in conffiles?

    ;;

    abort-upgrade)

    ;;

    *)
        echo "preinst called with unknown argument '$1'" >&2
        exit 1

    ;;

esac

exit 0
